name: Build NEO MANGA Extensions Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Execute Permission to Gradle
        run: chmod +x gradlew

      - name: Build Extensions Release Artifacts
        run: ./gradlew assembleRelease

      # --- الخطوة السحرية الجديدة لنشر الملفات تلقائياً ---
      - name: Deploy to repo branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: repo # الفرع السحري الذي سيتم إنشاؤه ونشر الملفات فيه
          folder: repo # المجلد الافتراضي الذي تتجمع فيه ملفات الـ JSON والـ APKs
          clean: true
